[project]

# Project info
site_name = "WaCS Photonics"
site_description = "The WaCS Photonics group documentation."
site_url = "https://www.example.com/"

# Navigation
nav = [
  { "Home" = "index.md" },
  { "Get started" = "get-started.md" },
  { "Admin" = [
        { "Human resources" = "admin/hr.md" },
        { "Purchases" = "admin/purchases.md" },
  ]},
  { "Organisation" = [
        { "Essential tools" = "organisation/tools.md" },
        { "Data management" = "organisation/data.md" }
  ]},
  { "Contribution" = [
        { "Zensical tutorial" = "contribution/zensical-doc.md" },
        "contribution/markdown.md",
  ]},
]

# Theme
[project.theme]
language = "en"

features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    # "navigation.sections",
    # "navigation.tabs",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]


[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

#[project.theme.font]
#text = "Inter"
#code = "Jetbrains Mono"

#[project.theme.icon]
#logo = "lucide/smile"
#repo = "lucide/smile"

# [[project.extra.social]]
# icon = "fontawesome/brands/github"
# link = "https://github.com/user/repo"


